"""Schemas for reading and replacing a workflow's graph."""

import uuid
from typing import Any, Self

from pydantic import BaseModel, Field, field_validator, model_validator

from app.nodes import DEFAULT_INPUT, DEFAULT_OUTPUT
from app.schemas.common import ORMModel

MAX_NODES = 200
MAX_EDGES = 400
HANDLE_MAX_LENGTH = 64


class Position(BaseModel):
    """Where a node sits on the canvas."""

    x: float = 0.0
    y: float = 0.0


class GraphNode(BaseModel):
    """A node as the editor sends it.

    The id is generated by the client so a node keeps its identity across
    saves, which lets run history keep pointing at it.
    """

    id: uuid.UUID
    type: str = Field(min_length=1, max_length=64)
    label: str = Field(min_length=1, max_length=120)
    configuration: dict[str, Any] = Field(default_factory=dict)
    position: Position = Field(default_factory=Position)

    @field_validator("label")
    @classmethod
    def _clean_label(cls, value: str) -> str:
        cleaned = " ".join(value.split())
        if not cleaned:
            raise ValueError("A node needs a label.")
        return cleaned


class GraphEdge(BaseModel):
    """A connection between two nodes."""

    id: uuid.UUID
    source: uuid.UUID
    target: uuid.UUID
    source_handle: str = Field(default=DEFAULT_OUTPUT, max_length=HANDLE_MAX_LENGTH)
    target_handle: str = Field(default=DEFAULT_INPUT, max_length=HANDLE_MAX_LENGTH)

    @model_validator(mode="after")
    def _reject_self_connections(self) -> Self:
        if self.source == self.target:
            raise ValueError("A node cannot be connected to itself.")
        return self


class GraphUpdate(BaseModel):
    """A complete replacement of the workflow's graph."""

    nodes: list[GraphNode] = Field(default_factory=list, max_length=MAX_NODES)
    edges: list[GraphEdge] = Field(default_factory=list, max_length=MAX_EDGES)

    @model_validator(mode="after")
    def _check_references(self) -> Self:
        node_ids = {node.id for node in self.nodes}
        if len(node_ids) != len(self.nodes):
            raise ValueError("Two nodes share the same id.")

        for edge in self.edges:
            if edge.source not in node_ids:
                raise ValueError(f"Edge {edge.id} starts at a node that is not in the graph.")
            if edge.target not in node_ids:
                raise ValueError(f"Edge {edge.id} ends at a node that is not in the graph.")

        connections = {
            (edge.source, edge.target, edge.source_handle, edge.target_handle)
            for edge in self.edges
        }
        if len(connections) != len(self.edges):
            raise ValueError("The same connection appears twice.")
        return self


class GraphNodeResponse(ORMModel):
    id: uuid.UUID
    type: str
    label: str
    configuration: dict[str, Any]
    position: Position


class GraphEdgeResponse(ORMModel):
    id: uuid.UUID
    source: uuid.UUID
    target: uuid.UUID
    source_handle: str
    target_handle: str


class WorkflowGraph(BaseModel):
    nodes: list[GraphNodeResponse]
    edges: list[GraphEdgeResponse]
